plugins {
    id 'application'
    id 'groovy'
    id 'jacoco'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.apache.groovy:groovy:4.0.23'
    implementation 'com.puppycrawl.tools:checkstyle:10.17.0'

    testImplementation libs.junit.jupiter
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'org.example.App'
}


sourceSets {
    main {
        groovy {
            srcDirs = ['src/main/groovy', 'src/main/java']
        }
        java {
            srcDirs = []
        }
    }
}

tasks.named('test') {
    useJUnitPlatform()
}


jar {
    manifest {
        attributes 'Main-Class': 'org.example.App'
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    exclude 'META-INF/*.SF'
    exclude 'META-INF/*.DSA'
    exclude 'META-INF/*.RSA'
    archiveFileName = 'oop-checker-all.jar'
}

jacocoTestReport {
    dependsOn test 
    reports {
        xml.required = true
        html.required = true
        csv.required = false
    }
}